# -*- coding: utf-8 -*-
"""Assignment1_SLP_Aulia(534388)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZj1VYsVCOONwD1P4OJUZn1_mSo6nQKp
"""

# Assignment 1 Deep Learning
# Single Layer Perceptron (SLP)
# Nama: Aulia Fathus Tsani
# NIM: 24/534388/PA/22661

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from IPython.display import display

# Mengambil dataset Iris
iris = load_iris()
data = pd.DataFrame(iris.data[:100], columns=["X1", "X2", "X3", "X4"])
data["Target"] = iris.target[:100]
data["Species"] = np.char.add(
    "Iris-", iris.target_names[iris.target[:100]]
)

print("DATASET IRIS")
display(data.head())

# Membagi data training dan validation
training_data = pd.concat([
    data.iloc[0:40],
    data.iloc[50:90]
]).reset_index(drop=True)

validation_data = pd.concat([
    data.iloc[40:50],
    data.iloc[90:100]
]).reset_index(drop=True)

X_train = training_data[["X1", "X2", "X3", "X4"]].to_numpy()
y_train = training_data["Target"].to_numpy()
X_validation = validation_data[["X1", "X2", "X3", "X4"]].to_numpy()
y_validation = validation_data["Target"].to_numpy()

# Membuat tabel pembagian data
pembagian_data = pd.DataFrame({
    "Jenis Data": ["Training", "Validation"],
    "Iris-setosa": [
        (training_data["Species"] == "Iris-setosa").sum(),
        (validation_data["Species"] == "Iris-setosa").sum()
    ],
    "Iris-versicolor": [
        (training_data["Species"] == "Iris-versicolor").sum(),
        (validation_data["Species"] == "Iris-versicolor").sum()
    ],
    "Total Data": [len(training_data), len(validation_data)]
})

print("\nPEMBAGIAN DATASET")
display(pembagian_data)


# Fungsi sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


# Menghitung output
def hitung_output(x, bias, bobot):
    return sigmoid(bias + np.dot(x, bobot))


# Menentukan prediksi
def hitung_prediksi(output):
    return 1 if output > 0.5 else 0


# Menghitung error
def hitung_error(output, target):
    return output - target


# Menghitung squared error
def hitung_squared_error(error):
    return error ** 2


# Menghitung MSE
def hitung_mse(daftar_squared_error):
    return np.mean(daftar_squared_error)


# Menghitung accuracy
def hitung_accuracy(prediksi, target):
    return np.mean(np.array(prediksi) == np.array(target)) * 100


# Memperbarui bobot dan bias
def update_bobot(x, output, error, bias, bobot, learning_rate):
    gradien = 2 * error * output * (1 - output)
    bias -= learning_rate * gradien
    bobot -= learning_rate * gradien * x
    return bias, bobot


# Proses training
def training_model(X, y, bias, bobot, learning_rate):
    daftar_prediksi = []
    daftar_squared_error = []

    for x, target in zip(X, y):
        output = hitung_output(x, bias, bobot)
        prediksi = hitung_prediksi(output)
        error = hitung_error(output, target)

        daftar_prediksi.append(prediksi)
        daftar_squared_error.append(hitung_squared_error(error))

        bias, bobot = update_bobot(
            x, output, error, bias, bobot, learning_rate
        )

    accuracy = hitung_accuracy(daftar_prediksi, y)
    mse = hitung_mse(daftar_squared_error)
    return bias, bobot, accuracy, mse


# Proses validation
def validation_model(X, y, bias, bobot):
    daftar_prediksi = []
    daftar_squared_error = []

    for x, target in zip(X, y):
        output = hitung_output(x, bias, bobot)
        prediksi = hitung_prediksi(output)
        error = hitung_error(output, target)

        daftar_prediksi.append(prediksi)
        daftar_squared_error.append(hitung_squared_error(error))

    accuracy = hitung_accuracy(daftar_prediksi, y)
    mse = hitung_mse(daftar_squared_error)
    return accuracy, mse


# Inisialisasi parameter
bias = 0.5
bobot = np.array([0.5, 0.5, 0.5, 0.5], dtype=float)
learning_rate = 0.1
jumlah_epoch = 5

training_accuracy, training_mse = [], []
validation_accuracy, validation_mse = [], []

# Menjalankan training dan validation
for epoch in range(1, jumlah_epoch + 1):
    bias, bobot, train_acc, train_loss = training_model(
        X_train, y_train, bias, bobot, learning_rate
    )

    val_acc, val_loss = validation_model(
        X_validation, y_validation, bias, bobot
    )

    training_accuracy.append(train_acc)
    training_mse.append(train_loss)
    validation_accuracy.append(val_acc)
    validation_mse.append(val_loss)

# Membuat tabel hasil
hasil = pd.DataFrame({
    "Epoch": range(1, jumlah_epoch + 1),
    "Training Accuracy (%)": training_accuracy,
    "Validation Accuracy (%)": validation_accuracy,
    "Training MSE": training_mse,
    "Validation MSE": validation_mse
})

print("\nHASIL TRAINING DAN VALIDATION")
display(hasil.round(6))

# Menyimpan tabel ke Excel
with pd.ExcelWriter("hasil_slp.xlsx") as writer:
    data.head().to_excel(writer, sheet_name="Data Awal", index=False)
    pembagian_data.to_excel(writer, sheet_name="Pembagian Data", index=False)
    hasil.round(6).to_excel(writer, sheet_name="Hasil Epoch", index=False)

# Grafik accuracy
epoch_range = range(1, jumlah_epoch + 1)

plt.figure(figsize=(8, 5))
plt.plot(
    epoch_range, training_accuracy,
    color="blue", marker="o",
    label="Training Accuracy"
)
plt.plot(
    epoch_range, validation_accuracy,
    color="red", marker="o",
    label="Validation Accuracy"
)
plt.title("Training vs Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.xticks(epoch_range)
plt.ylim(0, 105)
plt.grid(alpha=0.3)
plt.legend()
plt.tight_layout()
plt.savefig("01_accuracy_training_validation.png", dpi=150)
plt.show()

# Grafik MSE
plt.figure(figsize=(8, 5))
plt.plot(
    epoch_range, training_mse,
    color="blue", marker="o",
    label="Training Loss (MSE)"
)
plt.plot(
    epoch_range, validation_mse,
    color="red", marker="o",
    label="Validation Loss (MSE)"
)
plt.title("Training vs Validation Loss (MSE)")
plt.xlabel("Epoch")
plt.ylabel("Mean Squared Error")
plt.xticks(epoch_range)
plt.ylim(bottom=0)
plt.grid(alpha=0.3)
plt.legend()
plt.tight_layout()
plt.savefig("02_loss_training_validation.png", dpi=150)
plt.show()

print("Tabel dan grafik berhasil disimpan.")